# Generated by Django 5.0.14 on 2026-07-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='job',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
