# Generated by Django 5.0.14 on 2026-08-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_remove_resumeanalysis_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='My Resume', max_length=200),
        ),
    ]
